---
# handlers file for docker_ansible
- name: "run build.sh"
  command: "bash {{PROJECT_SRC}}build.sh"
  become_user: ori

- name: "run docker-compose.yaml"
  community.docker.docker_compose_v2:
    project_src: "{{PROJECT_SRC}}"
    state: present
    build: always
  become_user: ori